version: "3"

services:
  balancer:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - balancer
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/conf.d/default.conf

  web1:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - balancer
    volumes:
      - ./web1/index.html:/usr/share/nginx/html/index.html

  web2:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - balancer
    volumes:
      - ./web2/index.html:/usr/share/nginx/html/index.html

  web3_php:
    build:
      context: ./web3/docker/php
    networks:
      - balancer
    ports:
      - 9000:9000
    volumes:
      - ./web3/php:/srv/www/api
      - ./web3/docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web3_nginx:
    image: nginx:1.13.8
    ports:
      - 8082:80
    networks:
      - balancer
    volumes:
      - ./web3/php:/srv/www/api
      - ./web3/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web3_php

  web3_mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - balancer
    depends_on:
      - web3_php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  balancer:
